language: python
python:
  - "2.7"
  - "2.6"
install:
  - "pip install simplejson"
before_script:
  - "git clone https://github.com/alexz-enwp/wikitools.git"
  - "cd wikitools && python setup.py install"
script:
  - nosetests
