language: python
python:
  - "2.7"
  - "2.6"
  - "2.5"
  - "2.4"
install:
  - "pip install simplejson"
before_script:
  - "git clone https://github.com/alexz-enwp/wikitools.git . "
  - "rm CHANGELOG README setup.py"
script:
  - nosetests
